#!/bin/sh

. ~/.profile

bspc monitor --reset-desktops I II III IV V VI VII VIII IX X

bspc config top_padding "$PADDING"
bspc config right_padding "$PADDING"
bspc config bottom_padding "$PADDING"
bspc config left_padding "$PADDING"
bspc config window_gap "$PADDING"

bspc config border_width "$BORDER_WIDTH"
bspc config normal_border_color "$COLOUR_1"
bspc config active_border_color "$FOREGROUND_COLOUR"
bspc config focused_border_color "$HIGHLIGHT_COLOUR"

bspc config split_ratio 0.618
bspc config single_monocle true
bspc config gapless_monocle true
bspc config borderless_monocle true
bspc config paddingless_monocle true

bspc config click_to_focus true
bspc config focus_follows_pointer false
bspc config pointer_follows_focus false

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

bspc config honor_size_hints false
bspc config ignore_ewmh_focus false
bspc config initial_polarity first_child

# find the class name with: `xprop | grep WM_CLASS`
bspc rule --add "Firefox-esr" desktop="^2"
bspc rule --add "Chromium" desktop="^3"
bspc rule --add "Firefox Developer Edition" desktop="^4"
bspc rule --add "st-256color" --one-shot desktop="^5"
bspc rule --add "Keepassx" desktop="^10"

bspc wm --adopt-orphans

autostart
